### ISSUE TITLE
Outdoor Temperature Refresh

### ISSUE THREAD

**Issue by rcoletti116** [dotfortun3-code/homebridge-infinitude-v2#13]
How often should the OAT value refresh in homebridge? I’m finding it doesn’t update very frequently, but can’t figure out how often. Even a manual load of the device doesn’t refresh. 

The OAT value comes from the /api/status request which from the logs doesn’t seem to be called that often. 

I have only just noticed because I use this sensor in an automation during the summer months… from testing the issue exists from 0.6.0/0.6.1.

**Comment by rcoletti116** [comment]
And I have confirmed when the /status request is made the value is returned but not updated

```[11/05/2023, 16:05:29] [Infinitude] [VERBOSE] /api/status/ response: {"cfgem":["F"],"cfgtype":["heatcool"],"filtrlvl":["100"],"humid":["off"],"humlvl":["100"],"localTime":["2023-05-11T16:05:01-04:59"],"mode":["off"],"oat":["81"],"oprstsmsg":["idle"],"uvlvl":["100"],"vacatrunning":["off"],"ventlvl":["100"],"version":"1.7","zones":[]} ```

**Comment by rcoletti116** [comment]
I've been playing around with this and haven't yet found a solution. I implemented an updater and can successfully update the value every 2 minutes (my chosen interval). The next problem comes when after a restart the sensor isn't properly initialized. After a restart, Homebridge finds the sensor in cache, but it doesn't actually do anything. If you remove the items from cache the creation process works just fine, creates, configures, initializes and regularly updates... but once you restart your Homebridge instance it stops working.

**Comment by dotfortun3-code** [comment]
This should at least fix the outdoor sensor not re-initializing after HB is restarted.
