### ISSUE TITLE
Not refreshing

### ISSUE THREAD

**Issue by Kilonga** [dotfortun3-code/homebridge-infinitude-v2#7]
The plugin allows me to update the temperature directly under accessories inside homebridge or with the HomeKit thermostat but after a while it stops displaying the correct cooling temperature.  Even after changing it, it goes back to an older value.

**Comment by rcoletti116** [comment]
When the temperature reverts have you checked the infinitude dashboard to see what it displays as the current cooling temperature? You may need to narrow down if this issue is occurring between HomeKit and Infinitude or Infinitude and the thermostat.

**Comment by dotfortun3-code** [comment]
Closed due to inactivity
